name: mother-example
version: 0.1.0.0
github: "thepratt/mother"
license: BSD3
author: "Sam Pratt"
maintainer: "samj.pratt@gmail.com"
copyright: "2018 Sam Pratt"

description: Please see the README on Github at <https://github.com/thepratt/mother#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- mtl
- text
- wreq

executables:
  mother-example:
    main: Main.hs
    source-dirs: .
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Wall
      - -Werror
    dependencies:
      - mother-core