resolver: lts-8.15
allow-different-user: true

image:
  containers:
    - name: mother-example
      executables:
        - mother-example

packages:
  - location: mother-core
  - location: mother-example

extra-deps:
  - 'yaml-0.8.28'

flags: {}
